#liip_imagine:
#    driver: 'gd'
#    resolvers:
#        squared_thumbnail_small:
#            web_path:
#                web_root: "%kernel.project_dir%/public"
#                cache_prefix: "media/cache"
#    filter_sets:
#        cache: ~
#        squared_thumbnail_small:
#            filters:
#                thumbnail: { size: [200, 200], mode: outbound, allow_upscale: true }
#    loaders:
#        default:
#            filesystem:
#                data_root:
#                    - '%kernel.project_dir%/public'
liip_imagine:
    driver: 'gd'

    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.upload_filesystem_filesystem

    data_loader: flysystem_loader

#    resolvers:
#        flysystem_resolver:
#            flysystem:
#                filesystem_service: oneup_flysystem.upload_filesystem_filesystem
#                cache_prefix: media/cache
#                root_url: '/uploads'
#                visibility: public
#    cache: flysystem_resolver


    filter_sets:
        squared_thumbnail_small:
            filters:
                thumbnail:
                    size:          [200, 200]
                    mode:          outbound
                    allow_upscale: true
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    size: [ 400, 400 ]
                    mode: outbound
                    allow_upscale: true

