# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        upload_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
        upload_adapter_private:
            local:
                location: '%kernel.project_dir%/var/address_book_images'
    filesystems:
        upload_filesystem:
            adapter: upload_adapter
